
service: aws-scheduled-cron

provider:
  name: aws
  runtime: nodejs12.x

functions:
  cron:
    handler: handler.cronFunction
    # WORKSHOP_START
    # Step 1. In this_file, add a `schedule` event to trigger this function every minute. See `schedule` event docs: http://bit.ly/2ACbjVU
    # WORKSHOP_END
    # FINAL_START
    events:
      - schedule: rate(1 minute)
    # FINAL_END
