
service: step-functions-example

custom:
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  # Step 4. In this_file, reference the Output value of the state machine. ${self:resources.Outputs.MyStateMachine.Value} in the `environment` variables #
  # Step 5. In this_file, Attach the need `iamRoleStatements` to Allow access to step functions `states:*` #

functions:
  sendEmail:
    handler: handler.sendEmail
  startStateMachine:
    handler: handler.startStateMachine
    events:
      - http:
          path: start
          method: post
          cors: true

# Define the step function steps in the `stepFunctions` block

# Step 3. In this_file, Define the cloudformation outputs of the step function ARN. We will need this to reference as an environment variable of the service
