
service: event-driven-app

provider:
  name: aws
  runtime: nodejs12.x
  # WORKSHOP_START
  # Step 3. In this_file, add the database table name to the service's `environment` variables. The `aws-sdk` will need to know the table name in order to access the table
  # WORKSHOP_END
  # FINAL_START
  environment:
    # Here we reference the table name defined below. This is a cloud formation ref
    MY_TABLE: { Ref: myDynamoTable }
  # FINAL_END
  # WORKSHOP_START
  # Step 2. In this_file, add a new IAM role the lambda function needs in order to access the newly created dynamoDB table.
  # WORKSHOP_END
  # FINAL_START
  # Here we add a custom IAM statement to allow the function to access our dynamoDB Table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: { Fn::GetAtt: [ myDynamoTable, Arn ] }
  # FINAL_END

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true
  scan:
    handler: handler.scan
    events:
      - http:
          path: scan
          method: post
          cors: true

# WORKSHOP_START
# Step 1. Add the DynamoDB CloudFormation in `readme.md` to the `resources` block of this_file #
resources:
# WORKSHOP_END
# FINAL_START
resources:
  Resources:
    myDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'my-table-name'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
# FINAL_END
