
service: using-serverless-plugins

plugins:
  - serverless-manifest-plugin

custom:
  output:
    file: .serverless/manifest.json

provider:
  name: aws
  runtime: nodejs22.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
