
service: using-http-cors-example

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.functionWithCors
    events:
      - http:
          path: function-with-cors
          method: post
          cors: true
