
service: using-env-variables-example

# Step 1. In this_file, add an environment key & value to the `provider` section. This will allow all functions in the service to access the value. http://bit.ly/2yVp4CR #
provider:
  name: aws
  runtime: nodejs12.x

functions:
  foo:
    handler: handler.foo
    events:
      - http:
          path: foo
          method: get
  # Step 2. In this_file, add an environment variable to the `bar` function. Adding `environment` to the function level will scope the value to a single function. http://bit.ly/2yVp4CR #
  bar:
    handler: handler.bar
    events:
      - http:
          path: bar
          method: get
