
service: event-driven-app

provider:
  name: aws
  runtime: nodejs6.10
  # Step 3. In this_file, add the database table name to the service's `environment` variables. The `aws-sdk` will need to know the table name in order to access the table
  # Step 2. In this_file, add a new IAM role the lambda function needs in order to access the newly created dynamoDB table.

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true
  scan:
    handler: handler.scan
    events:
      - http:
          path: scan
          method: post
          cors: true

# Step 1. Add the DynamoDB CloudFormation in `readme.md` to the `resources` block of this_file #
resources:
