
service: using-dynamic-value

provider:
  name: aws
  runtime: nodejs12.x

functions:
  queryParamsExample:
    handler: handler.queryParamsExample
    events:
      - http:
          path: hello
          method: get
  pathParamsExample:
    handler: handler.pathParamsExample
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{name}
          method: get
